// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isdjmyazymlgnmwzjxkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZGpteWF6eW1sZ25td3pqeGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM0MjQsImV4cCI6MjA2NTU3OTQyNH0.U2Emc37lICzA6ckG7pwWDN5kzHw45Q7u-H-zWQFtB2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);